### ISSUE TITLE
ResetStick Delegate

### ISSUE THREAD

**Issue by riklowe** [MitrophD/Swift-SpriteKit-Analog-Stick#2]
I have been playing with this Joystick code for the last few days and have to say it is excellent.

One change I would suggest (which I have implemented in my version) is a resetStick Delegate.

This allows the owning program to detect when the user has released the joystick and perform required actions in their own application. e.g. I use it to centre the sights that are being controlled by the joystick.
Note : I only have one joystick in my app - may be more of an problem if you have two !

This is not an issue, just a suggestion, so I am happy for you to close this once you have read it.

best regards Richard

**Comment by MitrophD** [comment]
Hi Richard!Thank you for issue.
I added start & stop handlers.You can use it as:
``` swift
moveAnalogStick.startHandler = {
      
  // your code here...
}
```
&&
``` swift
moveAnalogStick.stopHandler = {
      
  // your code here...
}
```

**Comment by riklowe** [comment]
Thanks. Looks good
