### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by riklowe** [MitrophD/Swift-SpriteKit-Analog-Stick#3]
Hi

There seems to be an issue with this code - that stops the scene from correctly deInitialising 

I have modified your sample code by moving all of the joystick setup code out of the didMoveToView function into a separate function.

I added some print statements so I could see when initialisation and reinitialisation were happening

Additionally I added  willMoveFromView and  deinit functions as shown below

    override func didMoveToView(view: SKView) {

        print ("***** \(__FUNCTION__) *****")
        
        /* Setup your scene here */
        backgroundColor = UIColor.whiteColor()
        physicsBody = SKPhysicsBody(edgeLoopFromRect: frame)
        
        setupJoysticks() \\comment out to remove joystick from scene

        addApple(CGPointMake(CGRectGetMidX(frame), CGRectGetMidY(frame)))

   }
    
    override func willMoveFromView(view: SKView) {
        print ("***** \(__FUNCTION__) *****")
        
        self.removeAllChildren()
        self.removeAllActions()
        
        for sv in view.subviews {
            sv.removeFromSuperview()
        }
    }
    
    deinit {
        print ("***** \(__FUNCTION__) *****")
    }

So that I could get the scene to reload I changed the default clause in the touchesBegan to -

            default:
                //addApple(touch.locationInNode(self))

                let scene = GameScene()
                scene.scaleMode = .ResizeFill
                let transition = SKTransition.moveInWithDirection(SKTransitionDirection.Right, duration: 1)
                self.view?.presentScene(scene, transition: transition)

This means whenever you touch the screen - a new scene is loaded

With the setupJoysticks() code commented out (in didMoveToView) I get the following trace

***** didMoveToView *****
***** touchesBegan(_:withEvent:) *****
***** didMoveToView *****
***** willMoveFromView *****
***** deinit *****

With the setupJoysticks() code enabled (in didMoveToView) I get the following trace

***** didMoveToView *****
***** touchesBegan(_:withEvent:) *****
***** didMoveToView *****
***** willMoveFromView *****

The deinit NEVER happens.

This means that every time you instantiate a new scene - there is a memory leak
I am happy to send the demo project to you if it helps.

Best Regards
Richard

**Comment by MitrophD** [comment]
Sorry for my english
Hi Richard!This is because we use the strong references (GameScene has strong reference to AnalogJoystick.In turn AnalogJoystick has strong reference to GameScene in closures).
I use self here
``` swift
moveAnalogStick.startHandler = {
      
   guard let aN = self.appleNode else { return }
   aN.runAction(SKAction.sequence([SKAction.scaleTo(0.5, duration: 0.5), SKAction.scaleTo(1, duration: 0.5)]))
}

// && here

moveAnalogStick.trackingHandler = { data in
            
    guard let aN = self.appleNode else { return }
    aN.position = CGPointMake(aN.position.x + (data.velocity.x * 0.12), aN.position.y + (data.velocity.y * 0.12))
}
```
[ARC](https://en.wikipedia.org/wiki/Automatic_Reference_Counting) not reset the reference to the object  && he (self) will never be removed

There are three ways to solve the 
1. Use **unowned** (in demo project).Ex:
``` swift
moveAnalogStick.startHandler = { [unowned self] in
            
   guard let aN = self.appleNode else { return }
   aN.runAction(SKAction.sequence([SKAction.scaleTo(0.5, duration: 0.5), SKAction.scaleTo(1, duration: 0.5)]))
}
```
[unowned self]  - Changing self to unowned won't increase self 's retain count by 1, therefore allowing to ARC to deallocate it properly at the correct time.
2. Use **unowned** (in demo project).Ex:
``` swift
moveAnalogStick.startHandler = { [unowned self] in
            
   guard let aN = self.appleNode else { return }
   aN.runAction(SKAction.sequence([SKAction.scaleTo(0.5, duration: 0.5), SKAction.scaleTo(1, duration: 0.5)]))
}
```
[unowned self]  - Changing self to unowned won't increase self 's retain count by 1, therefore allowing to ARC to deallocate it properly at the correct time.
3. A few days later I upload version of the supported protocol

Happy coding Richard

**Comment by riklowe** [comment]
Thanks for the fast response - I will try some of above and let you know if I have any issues.

**Comment by riklowe** [comment]
Please note : I had to use [weak self] to get this to work properly.

When I used [unowned self] I got random errors when the new scene loaded
