### ISSUE TITLE
Multiple joystick

### ISSUE THREAD

**Issue by tekodragoon** [MitrophD/Swift-SpriteKit-Analog-Stick#4]
As i see in your demo project and in mine since i use your joystick (great job !), 
i notice that we can't move 2 joysticks in the same time.
Do you plan to enable such functionality ?

**Comment by MitrophD** [comment]
Hi Frédéric!Thank you for issue
Please add this code to didMoveToView method
``` swift
view.multipleTouchEnabled = true
```
So you turn on support multitouch

**Comment by tekodragoon** [comment]
I use it on a SCNView (on a overlaySKScene).
```
scnView = self.view as! SCNView
scnView.multipleTouchEnabled = true
```
Works fine now. Thank's for the tip
Now i can move and turn my sprite at the same time ;-)
And great job with your joystick

**Comment by TsepaStepan** [comment]
I'm sorry, but this code is still not working

**Comment by TsepaStepan** [comment]
can you help me

**Comment by MitrophD** [comment]
Hi Stepan.Show me your code please

**Comment by MitrophD** [comment]
сб, 21 янв. 2017 г. в 19:57, TsepaStepan <notifications@github.com>:

**Comment by TsepaStepan** [comment]
вот 
class GameScene: SKScene {
    
    // tanks and towers
    var tank1Tower: TankTower?
    var tank2Tower: TankTower?
    var tank1: Tank?
    var tank2: Tank?
    
    
    // joysticks
    var joystickTank1Tower: AnalogJoystick?
    var joystickTank2Tower: AnalogJoystick?
    
    var joystickTank1: AnalogJoystick?
    var joystickTank2: AnalogJoystick?
    
    
    override func didMove(to view: SKView) {
        createTanksAndTowers(CGPoint(x: -100, y: -100), CGPoint(x: 100, y: 100))
        createJoystick()
        self.physicsWorld.gravity = CGVector.zero
    }
    
    func createTanksAndTowers(_ pos1: CGPoint, _ pos2: CGPoint) {
        
        let tank1 = Tank(circleOfRadius: 75)
        tank1.position = pos1
        tank1.name = "tank1"
        tank1.physicsBody = SKPhysicsBody(circleOfRadius: 75)
        
        let tank1Tower = TankTower(color: UIColor.green, size: CGSize(width: 15, height: 100))
        tank1Tower.anchorPoint = CGPoint(x: 0.5, y: 0.1)
        tank1Tower.zPosition = 100
        tank1Tower.name = "tank1Tower"
        tank1Tower.physicsBody = SKPhysicsBody(rectangleOf: CGSize(width: 15, height: 100))
        tank1Tower.physicsBody?.pinned = true
        
        self.tank1 = tank1
        self.tank1Tower = tank1Tower
        
        tank1.addChild(tank1Tower)
        self.addChild(tank1)
        
    }
    
    func createJoystick() {
        joystickTank1Tower = AnalogJoystick(diameter: 110, colors: (UIColor.blue, UIColor.yellow))
//        joystickTank1Tower = Joystick()
        joystickTank1Tower?.position = CGPoint(x: -280, y: -390)
        joystickTank1Tower?.name = "joystick"
        joystickTank1Tower?.trackingHandler = { jData in
//            if let tower = self.tank1Tower {
//                tower.makeRotationStepTo(angle: jData.angular)
//            }
        }
        
        joystickTank1Tower?.stopHandler = { () -> Void in
            let tank1Tower = self.tank1Tower
            let tank1TowerRotation = -Double((tank1Tower?.zRotation)!)
            let towerVector = rotate(dx: 0.0, dy: 1.0, angle: tank1TowerRotation, length: 100.0)
            let buttonPosition = CGPoint(x: (self.tank1?.position.x)! + towerVector.dx, y: (self.tank1?.position.y)! + towerVector.dy)
            let bullet = SKShapeNode(circleOfRadius: 10)
            bullet.fillColor = UIColor.red
            bullet.position = buttonPosition
            bullet.physicsBody = SKPhysicsBody(circleOfRadius: 10)
            bullet.physicsBody?.velocity = multVector(vector: towerVector, mult: 5.0)
            self.addChild(bullet)
        }
        
        joystickTank1 = AnalogJoystick(diameter: 110, colors: (UIColor.green, UIColor.yellow))
        joystickTank1?.position = CGPoint(x: 280, y: -390)
        joystickTank1?.name = "joystick"
        
        joystickTank1?.trackingHandler = { jData in
            if let tank = self.tank1 {
                tank.physicsBody?.velocity = multVector(vector: CGVector(dx: jData.velocity.x, dy: jData.velocity.y), mult: 3.0)
            }
            
            if let tower = self.tank1Tower {
                if jData.angular > 0.1 {
                    tower.makeRotationStepTo(angle: jData.angular)
                }
            }
        }
        
        self.addChild(joystickTank1!)
        self.addChild(joystickTank1Tower!)
    }
}

**Comment by TsepaStepan** [comment]
а вот вьюконтроллер
class GameViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        if let view = self.view as! SKView? {
            // Load the SKScene from 'GameScene.sks'
            if let scene = SKScene(fileNamed: "GameScene") {
                // Set the scale mode to scale to fit the window
                scene.scaleMode = .aspectFill
                
                // Present the scene
                view.presentScene(scene)
            }
            
            view.ignoresSiblingOrder = true
            
            view.showsFPS = true
            view.showsNodeCount = true
            
            let scnView = self.view as! SKView
            scnView.isMultipleTouchEnabled = true
            
//            view.isMultipleTouchEnabled = true
        }
    }
    
    override var shouldAutorotate: Bool {
        return true
    }

    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        if UIDevice.current.userInterfaceIdiom == .phone {
            return .allButUpsideDown
        } else {
            return .all
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Release any cached data, images, etc that aren't in use.
    }

    override var prefersStatusBarHidden: Bool {
        return true
    }
}

**Comment by MitrophD** [comment]
сб, 21 янв. 2017 г. в 20:32, TsepaStepan <notifications@github.com>:

**Comment by TsepaStepan** [comment]
![p6l1nhbfxle](https://cloud.githubusercontent.com/assets/17403388/22176514/f1d983cc-e025-11e6-83e3-257140dde72c.jpg)

**Comment by TsepaStepan** [comment]
вот как выглядит моя игра

**Comment by TsepaStepan** [comment]
просто когда я сначала нажимаю и двигаю первый дж а потом нажимаю на второй и двигаю его то первый резетится

**Comment by TsepaStepan** [comment]
то есть он приходит в начальное положение

**Comment by TsepaStepan** [comment]
Hello everyone! for a long time i tried eliminate this issue. And finally i did it

**Comment by TsepaStepan** [comment]
the problem is that class AnalogJoystick must be inherited from SKSpriteNode, not from SKNode.

**Comment by TsepaStepan** [comment]
and you should write "super.init(texture: nil, color: UIColor.clear, size: diameter)", not "super.init()"

**Comment by TsepaStepan** [comment]
this is because when you touches joystick-1, and then, touches joystick-2, second touch location is in the joystick-1.parent // it is a SKNode. This is because class SKNode has not any size.

**Comment by TsepaStepan** [comment]
and if you will limit a size of parent of joystick, it will work fine

**Comment by TsepaStepan** [comment]
sorry for mistakes
