### ISSUE TITLE
Moveable Joystick, or position on first touch.

### ISSUE THREAD

**Issue by designspin** [MitrophD/Swift-SpriteKit-Analog-Stick#5]
Hi,

Firstly thanks for this great code, i'm actually using it in a game well into production and soon to be released.

One problem I have is the joystick location is obscuring areas where you need to see, I know the joystick can have transparency but when you place your thumb on it you can't see what lies beneath.

What would be great for me would be a way to make the pad appear at the location of your first touch and operate from there, if that makes sense? Then on touches end the joystick could disappear again. I could then use a second touch outside the joystick as a fire button. Is this something that could be implemented easily with the code as is? Or is it simply not possible?

Thanks again.

**Comment by mash3l777** [comment]
I have some problem do you solve it @designspin ?

**Comment by designspin** [comment]
@mash3l777, yes I did solve the problem with some extra coding, it was a while back I did it though. I think I was just adding the stick in on first touch. Take a look at https://itunes.apple.com/us/app/berks-3/id1380408196?mt=8 on the app store, currently free.

**Comment by MitrophD** [comment]
Hi guys! I solved your problems. You can download an example and ask if it is not clear. The description will be a little later, but without it is clear. Thanks for the feedback.
